---
vars:
  ospf_nbr:
    id: "{{ item.id }}"
    priority: "{{ item.priority }}"
    state: "{{ item.state }}"
    dead_time: "{{ item.dead_time }}"
    address: "{{ item.address }}"
    interface: "{{ item.interface }}"

keys:
  ospf_nbrs:
    value: "{{ ospf_nbr }}"
    items: "^(?P<id>\\d+\\.\\d+\\.\\d+.\\d+)\\s+(?P<priority>\\d)\\s+(?P<state>\\w+)\\/.*(?P<dead_time>\\d\\d:\\d\\d:\\d\\d)\\s+(?P<address>\\d+\\.\\d+\\.\\d+.\\d+)\\s+(?P<interface>.*)$"
