- name: Configure NTP
  arista.eos.eos_ntp_global:
    config:  
      servers:
        - server: "{{ item }}"
          vrf: "{{ mgmt_vrf }}"
          local_interface: "{{ eos_mgmt_intf }}"
      loop: "{{ ntp_server }}"