- name: Configure NTP
  cisco.ios.ios_ntp_global:
    config:
      servers:
        - server: "{{ item }}"
          vrf: "{{ mgmt_vrf }}"
          source: "{{ ios_mgmt_intf }}"
      loop: "{{ ntp_servers }}"