- name: Configure NTP
  cisco.iosxr.iosxr_ntp_global:
    config:
      servers:
        - server: "{{ item }}"
          vrf: "{{ mgmt_vrf }}"
          key: "{{ ntp_server_key }}"
          source: "{{ iosxr_mgmt_intf }}"
      loop: "{{ ntp_servers }}"