---
- name: Get ospf neighbor as structured data

  tasks:
    - name: Get ospf Neighbor Output
      iosxr_command:
        commands:
          - show ospf neighbors
      register: ospf_output

    - name: Parse Output to Variable
      set_fact:
        device_neighbors: "{{ ospf_output.stdout[0] | parse_cli_textfsm('/home/yuji/network_automation/templates/textfsm-templates/cisco_iosxr_show_ospf_neighbors.textfsm') }}"

    - name: Print Variable 
      debug:
        msg: "{{ device_neighbors }}"

    - name: Output to File
      
    - name: Print Neighbor
      debug:
        msg: "{{ item['LOCAL_INTERFACE'] }}: {{ item['NEIGHBOR'] }}"
      loop: "{{ device_neighbors }}"
      loop_control:
        label: "{{ item['LOCAL_INTERFACE'] }}"