- name: Run Command and parse with textfsm
  ansible.utils.cli_parse:
    command: show lldp neighbor
    parser:
      name: ansible.utils.textfsm
      template_path: /home/yuji/network_automation/templates/textfsm_templates/cisco_nxos_show_lldp_neighbors.textfsm
    set_fact: lldp_neighbor
