- name: ensuire netconf is running
  vars:
    ansible_connection: network_cli
  junos_netconf:

- name: backup junos configuration
  vars:
    ansible_connection: netconf
  junipernetworks.junos.junos_config:
    backup: true
    backup_options:
      dir_path: /tmp/
      filename: "{{ inventory_hostname }}"      
  register: config_output
