- name: Get Datetime
  set_fact:
    datetime: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M') }}"
  run_once: true

- name: ensure directory exists
  file:
    path: /home/yuji/network_automation/output/backup/{{ datetime }}
    state: directory
  run_once: true
  
- name: backup network device config
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/tasks/{{ ansible_network_os }}.yml"
    - "{{ role_path }}/tasks/unsupported_platform.yml"
