- name: Configure SNMP Group and Host
  cisco.ios.ios_snmp_server:
    config:
      communities:
      - acl_v4: "{{ snmp_acl }}"
        rw: true

      groups:
      - group: "{{ snmp_v3_group_name }}"
        version: v3
        version_option: priv
 
      hosts:
      - host: "{{ snmp_ipv4_servers }}"
        version: v3
        version_option: priv
        vrf: "{{ mgmt_vrf }}" 
        loop: "{{ snmp_ipv4_servers }}"
      
      users:
      - group: "{{ snmp_v3_groupname }}"
        username: "{{ snmp_v3_username }}"
        version: v3
