- hosts: dnac_servers
  vars_files:
    - credentials.yml
  gather_facts: no
  tasks:
  - name: Create an sda_fabric
    cisco.dnac.sda_fabric:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_debug: "{{dnac_debug}}"
      state: present
      fabricName: "MyFabricName2"
      payload:
        - fabricName: "MyFabricName2"
    register: sda_fabric_result

  - name: Show new sda_fabric
    debug:
      msg: "{{ sda_fabric_result }}"
    when:
      - sda_fabric_result is defined
