---
- name: Configure DNS
  hosts: yuji_lab
  gather_facts: no
  vars_files:
    - ../inventory/group_vars/yuij_lab.yml
  
  tasks:
    - name: Configure DNS
      include_role:
        name: "../roles/config_dns"
