---
- name: Configure DNS
  hosts: yuji_lab
  connection: network_cli
  gather_facts: no
  become: yes
  
  tasks:
    - name: Configure SNMP
      include_role:
        name: ../roles/config_dns
      dns-servers: "192.168.10.10"