---
- name: Get Interface info
  hosts: yuji_lab
  gather_facts: no

    - name: Get Datetime
      include_role:
        name: "../roles/get_datetime"
      run_once: true

    - name: Include show interface role
      include_role:
        name: "../roles/show_interface"

#- name: Print Variable 
#  debug:
#    msg: "{{ interfaces }}"