---
- name: Get OSPF info
  hosts: yuji_lab
  gather_facts: no

  tasks:
    - name: Get Datetime
      set_fact:
        datetime: "{{ lookup('pipe','date +%Y%m%d%H%M') }}"
      run_once: true

    - name: ensure directory exists
      file:
        path: /home/yuji/network_automation/output/ospf_neighbor/{{ datetime }}
        state: directory
      run_once: true
        
    - name: ensure file exists
      file:
        path: /home/yuji/network_automation/output/ospf_neighbor/{{ datetime }}/{{ inventory_hostname }}_ospf_neighbor
        state: touch

    - name: Include show ospf neighbor role
      include_role:
        name: "../roles/show_ospf_neighbor"

    - name: Copy output to file
      local_action: 
        module: copy 
        content: "{{ ospf_neighbors | to_nice_json }}" 
        dest: /home/yuji/network_automation/output/ospf_neighbor/{{ datetime }}/{{ inventory_hostname }}_ospf_neighbor
