---
- name: Get Interface info
  hosts: yuji_lab
  gather_facts: no

  tasks:
    - name: Get Datetime
      set_fact:
        datetime: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M') }}"
      run_once: true

    - name: Include show interface role
      include_role:
        name: "../roles/show_interface"

#- name: Print Variable 
#  debug:
#    msg: "{{ interfaces }}"