---
- name: Get router facts
  hosts: yuji_lab 
  connection: network_cli
  gather_facts: yes

  tasks:

    - name: Copy output to file
      copy:
        content: "{{ ansible_facts }}" 
        dest: /home/yuji/network_automation/output/interfaces_ntc/{{ datetime }}/{{ inventory_hostname }}_facts
