---
- name: Get ospf info
  hosts: yuji_lab
  gather_facts: no

  tasks:
    - name: Get Datetime
      set_fact:
        datetime: "{{ lookup('pipe','date +%Y%m%d%H%M') }}"
      run_once: true

    - name: ensure directory exists
      file:
        path: /home/yuji/network_automation/output/ospf_database_ntc/{{ datetime }}
        state: directory
      run_once: true
        
#    - name: ensure file exists
#      file:
#        path: /home/yuji/network_automation/output/ospf_database_ntc/{{ datetime }}/{{ inventory_hostname }}_ospf_database_ntc
#        state: touch

    - name: Include show ospf database role
      include_role:
        name: "../roles/show_ospf_database_ntc"

    - name: Copy output to JSON file
      copy:
        content: "{{ ospf_database | to_nice_json }}" 
        dest: /home/yuji/network_automation/output/ospf_database_ntc/{{ datetime }}/{{ inventory_hostname }}_ospf_database_ntc.json

    - name: Copy output to YAML file
      copy:
        content: "{{ ospf_database | to_nice_yaml }}" 
        dest: /home/yuji/network_automation/output/ospf_database_ntc/{{ datetime }}/{{ inventory_hostname }}_ospf_database_ntc.yml