---
- name: Get Interface info
  hosts: yuji_lab
  gather_facts: no

  tasks:
    - name: Include show interface role
      include_role:
        name: "../roles/show_interface_ntc"

#- name: Print Variable 
#  debug:
#    msg: "{{ interfaces }}"